"use client";

import React, { useState, useRef, useEffect, MouseEvent } from "react";

// ─── Types ─────────────────────────────────────────────────────────────────────

interface Service {
  number: string;
  title: string;
  description: string;
  color: string;
}

interface Deliverable {
  icon: string;
  title: string;
  description: string;
}

interface FAQ {
  question: string;
  answer: string;
}

interface Metric {
  value: string;
  label: string;
}

interface ProofStat {
  value: string;
  label: string;
  color: string;
}

// ─── Data ──────────────────────────────────────────────────────────────────────

const services: Service[] = [
  {
    number: "01",
    title: "Outbound Prospecting",
    description:
      "We identify, research, and reach out to your ideal buyers directly — with personalised cold email and LinkedIn sequences built around their actual pain points, not a generic pitch template. Quality of targeting beats volume of outreach every time.",
    color: "#E8456A",
  },
  {
    number: "02",
    title: "Inbound Lead Capture",
    description:
      "Landing pages, lead magnets, gated content, and conversion-optimised forms that turn your existing traffic into a measurable pipeline. We design, build, and A/B test every capture point so you know exactly what's working and why.",
    color: "#7B5EA7",
  },
  {
    number: "03",
    title: "Lead Qualification & Scoring",
    description:
      "Not every lead is worth your sales team's time. We build scoring models based on your ICP criteria — company size, intent signals, behaviour data — so your reps only work with contacts who are genuinely ready to buy.",
    color: "#2BB5A0",
  },
  {
    number: "04",
    title: "CRM Setup & Pipeline Management",
    description:
      "Leads mean nothing without a clean system to work them. We set up or audit your CRM, build the pipeline stages that reflect your actual sales process, and make sure every lead is tracked, followed up, and never falls through the cracks.",
    color: "#F4A432",
  },
];

const deliverables: Deliverable[] = [
  {
    icon: "🎯",
    title: "ICP Definition & Target List",
    description:
      "A granular ideal customer profile built from your best existing clients — with firmographic filters, technographic signals, and a verified prospect list of 500–1,000 contacts to kick off outbound.",
  },
  {
    icon: "📬",
    title: "Outbound Sequence (6–8 touchpoints)",
    description:
      "A fully written multi-step outbound sequence — cold email, LinkedIn connection, follow-ups, and a breakup message — personalised by segment and tested for reply rate from week one.",
  },
  {
    icon: "🏗️",
    title: "Lead Capture Infrastructure",
    description:
      "Landing pages, lead magnet assets, form builds, and thank-you page sequences — all connected to your CRM and tracked with conversion events so you can see exactly where leads come from.",
  },
  {
    icon: "⚙️",
    title: "Lead Scoring Model",
    description:
      "A scoring framework built in your CRM that grades every inbound lead against your ICP criteria, intent behaviour, and engagement history — so sales always knows who to call first.",
  },
  {
    icon: "🔗",
    title: "CRM Build & Integration",
    description:
      "HubSpot, Salesforce, or Pipedrive — set up correctly, with deal stages that match your sales motion, automation rules, and integrations with your email and ad platforms.",
  },
  {
    icon: "📊",
    title: "Weekly Lead Report",
    description:
      "A concise weekly report covering leads generated by source, qualification rate, pipeline value added, and outbound reply metrics — so you always know what the engine is producing.",
  },
];

const faqs: FAQ[] = [
  {
    question: "What's the difference between a lead and a qualified lead?",
    answer:
      "A lead is anyone who's expressed some form of interest — filled in a form, replied to an email, clicked an ad. A qualified lead is someone who matches your ICP, has the budget and authority to buy, and is at a stage in their journey where a sales conversation makes sense. We focus on the second kind. Filling a spreadsheet with cold contacts is easy. Producing pipeline that sales can actually close is the job.",
  },
  {
    question: "How quickly can you start generating leads?",
    answer:
      "Outbound sequences can be live within 10–14 days of onboarding. Inbound infrastructure — landing pages, lead magnets, CRM setup — typically takes 3–4 weeks to build correctly. We don't rush the setup because a poorly configured lead capture system or CRM creates problems that compound over time. The first 30 days is infrastructure; the returns come from month two onwards.",
  },
  {
    question: "Which CRMs do you work with?",
    answer:
      "We work primarily with HubSpot, Salesforce, and Pipedrive. We also have experience with Zoho CRM and Monday Sales CRM. If you don't have a CRM yet, we'll recommend the right one for your team size, deal complexity, and budget — and build it from scratch as part of the engagement.",
  },
  {
    question: "Do you handle the outreach yourselves or do we?",
    answer:
      "We handle everything — prospect research, list building, sequence writing, sending infrastructure setup, inbox monitoring, and reply management. Your sales team gets a warm handoff when a lead expresses genuine interest. The only thing we need from you is 30 minutes in week one to align on ICP and messaging.",
  },
  {
    question: "How do you avoid getting flagged as spam?",
    answer:
      "Deliverability is foundational to outbound. We set up dedicated sending domains, warm them up properly over 3–4 weeks, keep daily send volumes conservative, personalise at scale using verified data, and maintain strict bounce and unsubscribe suppression. We also monitor reply rates and spam complaint rates weekly — and pull back immediately if either signals a problem.",
  },
  {
    question: "What volume of leads should we expect?",
    answer:
      "Volume depends on your ICP size, market, and whether we're running outbound, inbound, or both. What we commit to is quality over quantity — we'd rather deliver 40 well-qualified leads per month than 400 contacts who'll never buy. We set realistic expectations in the scoping call and hold ourselves to them in the weekly report.",
  },
];

const stats: Metric[] = [
  { value: "3.4×", label: "Avg. pipeline growth at 90 days" },
  { value: "68%", label: "Avg. lead qualification rate" },
  { value: "₹290", label: "Avg. cost per qualified lead" },
  { value: "14d", label: "Avg. to first outbound live" },
];

const proofStats: ProofStat[] = [
  {
    value: "420",
    label: "Qualified leads delivered in 90 days for a B2B logistics SaaS — against a target of 300",
    color: "#E8456A",
  },
  {
    value: "5.1×",
    label: "Pipeline value generated vs retainer cost in the first six months",
    color: "#7B5EA7",
  },
  {
    value: "31%",
    label: "Cold email reply rate achieved through hyper-personalised sequencing — industry average is 8%",
    color: "#2BB5A0",
  },
];

const dotColors = ["#5B4FCF", "#2BB5A0", "#F4A432", "#E8456A", "#5BBF5B"];

// ─── Shared components ─────────────────────────────────────────────────────────

const Container = ({
  children,
  className = "",
}: {
  children: React.ReactNode;
  className?: string;
}) => (
  <div
    className={`w-full max-w-[1400px] mx-auto px-6 sm:px-8 lg:px-16 xl:px-24 ${className}`}
  >
    {children}
  </div>
);

const useReveal = (delay = 0) => {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setVisible(true);
          obs.disconnect();
        }
      },
      { threshold: 0.1 }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, []);
  return {
    ref,
    style: {
      opacity: visible ? 1 : 0,
      transform: visible ? "translateY(0)" : "translateY(28px)",
      transition: `opacity 0.6s ease ${delay}ms, transform 0.6s ease ${delay}ms`,
    },
  };
};

const MagneticCTA = ({
  href,
  children,
  dark = false,
}: {
  href: string;
  children: React.ReactNode;
  dark?: boolean;
}) => {
  const ref = useRef<HTMLAnchorElement>(null);
  const onMove = (e: MouseEvent<HTMLAnchorElement>) => {
    const el = ref.current;
    if (!el) return;
    const r = el.getBoundingClientRect();
    el.style.transform = `translate(${(e.clientX - r.left - r.width / 2) * 0.3
      }px, ${(e.clientY - r.top - r.height / 2) * 0.3}px)`;
  };
  const onLeave = () => {
    if (ref.current) ref.current.style.transform = "translate(0,0)";
  };
  return (
    <a
      ref={ref}
      href={href}
      onMouseMove={onMove}
      onMouseLeave={onLeave}
      className={`inline-flex items-center gap-2 text-[11px] font-semibold tracking-widest uppercase px-6 py-3 rounded-full border transition-all duration-200 ${dark
        ? "bg-white text-black border-white hover:bg-transparent hover:text-white"
        : "bg-black text-white border-black hover:bg-transparent hover:text-black"
        }`}
      style={{ transition: "transform 0.15s ease, background 0.2s, color 0.2s" }}
    >
      {children}
    </a>
  );
};

const SectionLabel = ({
  color,
  children,
}: {
  color: string;
  children: React.ReactNode;
}) => (
  <span
    className="text-[11px] font-semibold tracking-widest uppercase mb-4 block"
    style={{ color }}
  >
    {children}
  </span>
);

// ─── Section-specific components ───────────────────────────────────────────────

const ServiceCard = ({
  service,
  index,
}: {
  service: Service;
  index: number;
}) => {
  const { ref, style } = useReveal(index * 100);
  const [hovered, setHovered] = useState(false);
  return (
    <div
      ref={ref}
      style={
        hovered
          ? {
            ...style,
            transform: "translateY(-4px)",
            boxShadow: `0 16px 40px ${service.color}20`,
          }
          : style
      }
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      className="relative bg-white rounded-2xl p-6 border border-black/[0.06] transition-all duration-300 cursor-default overflow-hidden"
    >
      <div
        className="absolute top-0 left-0 w-1 h-full rounded-l-2xl transition-all duration-300"
        style={{ backgroundColor: service.color, opacity: hovered ? 1 : 0.4 }}
      />
      <span
        className="text-[11px] font-bold tracking-widest mb-3 block"
        style={{ color: service.color }}
      >
        {service.number}
      </span>
      <h3 className="font-serif text-lg font-normal text-black mb-2 leading-snug">
        {service.title}
      </h3>
      <p className="text-gray-500 text-sm leading-relaxed">{service.description}</p>
    </div>
  );
};

const DeliverableCard = ({
  item,
  index,
}: {
  item: Deliverable;
  index: number;
}) => {
  const { ref, style } = useReveal(index * 80);
  const [hovered, setHovered] = useState(false);
  return (
    <div
      ref={ref}
      style={
        hovered
          ? {
            ...style,
            backgroundColor: "rgba(255,255,255,0.15)",
            transform: "translateY(-3px)",
          }
          : style
      }
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      className="bg-white/10 rounded-2xl p-5 border border-white/10 transition-all duration-300"
    >
      <span className="text-2xl mb-3 block">{item.icon}</span>
      <h4 className="font-serif text-base font-normal text-white mb-2">
        {item.title}
      </h4>
      <p className="text-white/50 text-xs sm:text-sm leading-relaxed">
        {item.description}
      </p>
    </div>
  );
};

const FAQItem = ({ faq, index }: { faq: FAQ; index: number }) => {
  const [open, setOpen] = useState(false);
  const { ref, style } = useReveal(index * 80);
  return (
    <div
      ref={ref}
      style={style}
      className="border-b border-black/10 last:border-b-0"
    >
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between py-5 text-left gap-4 group"
      >
        <span className="font-serif text-base sm:text-lg font-normal text-black leading-snug group-hover:text-gray-600 transition-colors duration-200">
          {faq.question}
        </span>
        <span
          className="flex-shrink-0 w-7 h-7 rounded-full border border-black/15 flex items-center justify-center text-sm transition-all duration-300"
          style={{
            transform: open ? "rotate(45deg)" : "rotate(0deg)",
            backgroundColor: open ? "#1a1a1a" : "transparent",
            color: open ? "white" : "#1a1a1a",
          }}
        >
          +
        </span>
      </button>
      <div
        className="overflow-hidden"
        style={{
          maxHeight: open ? "400px" : "0px",
          transition: "max-height 0.4s ease",
        }}
      >
        <p className="text-gray-500 text-sm leading-relaxed pb-5 pr-10">
          {faq.answer}
        </p>
      </div>
    </div>
  );
};

// ─── Page ──────────────────────────────────────────────────────────────────────

const LeadGenerationPage = () => {
  const [titleVisible, setTitleVisible] = useState(false);
  useEffect(() => {
    const t = setTimeout(() => setTitleVisible(true), 100);
    return () => clearTimeout(t);
  }, []);

  const fadeIn = (delay: number) => ({
    opacity: titleVisible ? 1 : 0,
    transform: titleVisible ? "translateY(0)" : "translateY(20px)",
    transition: `opacity 0.7s ease ${delay}ms, transform 0.7s ease ${delay}ms`,
  });

  // Section reveal hooks — all at top level, no IIFEs
  const { ref: whatWeDoLeftRef, style: whatWeDoLeftStyle } = useReveal(0);
  const { ref: whatWeDoRightRef, style: whatWeDoRightStyle } = useReveal(120);
  const { ref: servicesLeftRef, style: servicesLeftStyle } = useReveal(0);
  const { ref: deliverablesLeftRef, style: deliverablesLeftStyle } = useReveal(0);
  const { ref: proofLeftRef, style: proofLeftStyle } = useReveal(0);
  const { ref: whoLeftRef, style: whoLeftStyle } = useReveal(0);
  const { ref: faqLeftRef, style: faqLeftStyle } = useReveal(0);
  const { ref: ctaLeftRef, style: ctaLeftStyle } = useReveal(0);
  const { ref: ctaRightRef, style: ctaRightStyle } = useReveal(150);

  // "Who it's for" rows
  const { ref: whoReveal0Ref, style: whoReveal0Style } = useReveal(0);
  const { ref: whoReveal1Ref, style: whoReveal1Style } = useReveal(100);
  const { ref: whoReveal2Ref, style: whoReveal2Style } = useReveal(200);
  const whoRevealRefs = [whoReveal0Ref, whoReveal1Ref, whoReveal2Ref];
  const whoRevealStyles = [whoReveal0Style, whoReveal1Style, whoReveal2Style];

  const whoItems = [
    {
      label: "B2B SaaS",
      color: "#E8456A",
      description:
        "Long sales cycles mean you need a consistent stream of qualified opportunities just to hit your quarterly targets. We build the outbound and inbound infrastructure that keeps your pipeline full — without your founders doing the prospecting.",
    },
    {
      label: "Professional Services",
      color: "#7B5EA7",
      description:
        "Consultants, agencies, and service firms that have grown on referrals and want a repeatable acquisition channel that doesn't depend on who you happen to know. We build the systems that put you in front of the right buyers consistently.",
    },
    {
      label: "Enterprise Sales Teams",
      color: "#2BB5A0",
      description:
        "Your reps are expensive and their time is finite. We handle the top-of-funnel research, prospecting, and initial outreach so your closers spend their hours on conversations that actually have a chance of converting.",
    },
  ];

  return (
    <main className="bg-[#F5F0E8] min-h-screen pt-[72px] overflow-x-hidden">

      {/* ── HERO ── */}
      <section className="py-14 sm:py-20">
        <Container>
          <div className="grid grid-cols-1 lg:grid-cols-[55%_45%] gap-8 lg:gap-10 items-center">

            {/* Left */}
            <div>
              <div className="inline-flex items-center gap-2 mb-6" style={fadeIn(100)}>
                <div className="flex gap-1.5">
                  {dotColors.map((c, i) => (
                    <span
                      key={i}
                      className="w-2.5 h-2.5 rounded-full"
                      style={{ backgroundColor: c }}
                    />
                  ))}
                </div>
                <span className="text-[11px] font-semibold tracking-widest uppercase text-gray-500">
                  Our Services
                </span>
              </div>

              <h1
                className="font-serif text-4xl sm:text-4xl md:text-5xl lg:text-5xl xl:text-6xl font-normal text-black leading-[1.0] mb-6"
                style={fadeIn(200)}
              >
                Leads your sales<br />
                team will{" "}
                <em className="not-italic" style={{ color: "#7B5EA7" }}>
                  actually
                </em>
                <br />
                want to call.
              </h1>

              <p
                className="text-gray-500 text-sm sm:text-base leading-relaxed mb-10"
                style={fadeIn(350)}
              >
                Most lead generation produces volume without quality — a spreadsheet
                full of contacts who were never going to buy, handed to a sales team
                that loses trust in marketing a little more each week. We build lead
                generation systems that are obsessive about fit, ruthless about
                qualification, and measured on pipeline value — not contact count.
              </p>

              <div
                className="flex flex-wrap items-center gap-4"
                style={fadeIn(480)}
              >
                <MagneticCTA href="/contact">Build My Pipeline →</MagneticCTA>
                <a
                  href="#services"
                  className="text-[11px] font-semibold tracking-widest uppercase text-black border-b border-black/30 pb-0.5 hover:border-black transition-all duration-200"
                >
                  See How We Do It ↓
                </a>
              </div>
            </div>

            {/* Right — stats + testimonial */}
            <div
              className="bg-white rounded-3xl p-8 border border-black/[0.06]"
              style={fadeIn(300)}
            >
              <div className="grid grid-cols-2 gap-6 mb-8">
                {stats.map((s) => (
                  <div key={s.label} className="bg-[#F5F0E8] rounded-2xl p-5">
                    <p className="font-serif text-3xl font-normal text-black mb-1">
                      {s.value}
                    </p>
                    <p className="text-[10px] font-medium tracking-widest uppercase text-gray-400">
                      {s.label}
                    </p>
                  </div>
                ))}
              </div>

              <div className="border-t border-black/8 pt-6">
                <div className="flex gap-1 mb-3">
                  {[...Array(5)].map((_, i) => (
                    <span key={i} style={{ color: "#F4A432", fontSize: "14px" }}>
                      ★
                    </span>
                  ))}
                </div>
                <p className="font-serif text-sm text-black leading-relaxed mb-4">
                  &quot;We&apos;d been burning budget on ads that produced clicks but no
                  pipeline. Social Manch rebuilt our lead gen from the ground up —
                  60 days later our sales team had more qualified conversations than
                  the entire previous quarter.&quot;
                </p>
                <div className="flex items-center gap-3">
                  <div
                    className="w-8 h-8 rounded-full flex items-center justify-center font-semibold text-xs flex-shrink-0"
                    style={{ backgroundColor: "#7B5EA720", color: "#7B5EA7" }}
                  >
                    AS
                  </div>
                  <div>
                    <p className="text-xs font-semibold text-black">Arjun Sethi</p>
                    <p className="text-[10px] text-gray-400">
                      VP Sales, Vendora B2B
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Container>
      </section>

      {/* ── WHAT WE DO ── */}
      <section className="border-t border-black/10 py-16 sm:py-24">
        <Container>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-20 items-start">
            <div ref={whatWeDoLeftRef} style={whatWeDoLeftStyle}>
              <SectionLabel color="#E8456A">✦ What We Do</SectionLabel>
              <h2 className="font-serif text-3xl sm:text-4xl lg:text-5xl xl:text-5xl font-normal text-black leading-snug">
                The problem isn&apos;t lead volume. It&apos;s lead quality.
              </h2>
            </div>
            <div
              ref={whatWeDoRightRef}
              style={whatWeDoRightStyle}
              className="space-y-5 pt-1"
            >
              <p className="text-gray-500 text-sm leading-relaxed">
                Sales teams that don&apos;t trust marketing leads go back to doing their
                own prospecting. That&apos;s expensive, inconsistent, and it means your
                marketing budget is producing nothing except friction between two
                teams that should be working together.
              </p>
              <p className="text-gray-500 text-sm leading-relaxed">
                The fix isn&apos;t more leads — it&apos;s better ones. We start every
                engagement by defining what a qualified lead actually looks like for
                your business, building the scoring model that identifies them
                reliably, and then designing the outbound and inbound systems that
                produce them at scale.
              </p>
              <p className="text-gray-500 text-sm leading-relaxed">
                The result is a lead generation engine that your sales team believes
                in — because the leads it produces consistently turn into pipeline
                that closes.
              </p>
            </div>
          </div>
        </Container>
      </section>

      {/* ── SERVICES ── */}
      <section id="services" className="border-t border-black/10 py-16 sm:py-24">
        <Container>
          <div className="grid grid-cols-1 lg:grid-cols-[1fr_2fr] gap-10 lg:gap-20 items-start">
            <div
              ref={servicesLeftRef}
              style={servicesLeftStyle}
              className="lg:sticky lg:top-28"
            >
              <SectionLabel color="#7B5EA7">✦ How We Do It</SectionLabel>
              <h2 className="font-serif text-3xl sm:text-4xl lg:text-5xl font-normal text-black leading-snug">
                Four levers.<br />
                One pipeline<br />
                <em>machine.</em>
              </h2>
              <p className="text-gray-500 text-sm leading-relaxed mt-4">
                Outbound finds buyers who don&apos;t know you yet. Inbound captures the
                ones already looking. Qualification filters both. CRM makes sure
                nothing gets lost. Together, they&apos;re a system.
              </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {services.map((service, i) => (
                <ServiceCard key={service.number} service={service} index={i} />
              ))}
            </div>
          </div>
        </Container>
      </section>

      {/* ── DELIVERABLES (dark) ── */}
      <section className="bg-[#1a1a1a] py-16 sm:py-24 relative overflow-hidden">
        <div
          className="absolute w-64 h-64 rounded-full bg-[#7B5EA7] opacity-10 -top-20 -right-20 pointer-events-none"
          style={{ animation: "floatA 9s ease-in-out infinite" }}
        />
        <div
          className="absolute w-40 h-40 rounded-full bg-[#E8456A] opacity-10 bottom-0 left-10 pointer-events-none"
          style={{ animation: "floatB 11s ease-in-out infinite" }}
        />
        <Container className="relative z-10">
          <div className="grid grid-cols-1 lg:grid-cols-[1fr_2fr] gap-10 lg:gap-20 items-start">
            <div
              ref={deliverablesLeftRef}
              style={deliverablesLeftStyle}
              className="lg:sticky lg:top-28"
            >
              <SectionLabel color="#7B5EA7">✦ What You Get</SectionLabel>
              <h2 className="font-serif text-3xl sm:text-4xl lg:text-5xl font-normal text-white leading-snug">
                Six things that<br />fill your pipeline.
              </h2>
              <p className="text-white/40 text-sm leading-relaxed mt-4">
                Every deliverable built to work together — from the first prospect
                touch to a CRM-tracked opportunity your sales team can close.
              </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {deliverables.map((item, i) => (
                <DeliverableCard key={item.title} item={item} index={i} />
              ))}
            </div>
          </div>
        </Container>
      </section>

      {/* ── PROOF ── */}
      <section className="border-t border-black/10 py-16 sm:py-24">
        <Container>
          <div className="grid grid-cols-1 lg:grid-cols-[1fr_2fr] gap-10 lg:gap-20 items-start">
            <div ref={proofLeftRef} style={proofLeftStyle} className="lg:sticky lg:top-28">
              <SectionLabel color="#F4A432">✦ Proof</SectionLabel>
              <h2 className="font-serif text-3xl sm:text-4xl lg:text-5xl font-normal text-black leading-snug">
                Pipeline numbers,<br />not<br />
                <em>activity metrics.</em>
              </h2>
              <p className="text-gray-500 text-sm leading-relaxed mt-4">
                Results from clients we&apos;ve worked with for 6+ months. We&apos;ll walk
                you through the specifics on a call — no aggregated averages, no
                cherry-picked outliers.
              </p>
            </div>

            <div className="space-y-4">
              {proofStats.map((r) => (
                <div
                  key={r.label}
                  className="bg-white rounded-2xl p-7 border border-black/[0.06] flex items-center gap-6"
                >
                  <span
                    className="font-serif text-4xl sm:text-5xl font-normal flex-shrink-0"
                    style={{ color: r.color }}
                  >
                    {r.value}
                  </span>
                  <p className="text-gray-500 text-sm leading-relaxed">{r.label}</p>
                </div>
              ))}

              {/* Testimonial */}
              <div className="bg-white rounded-2xl p-7 border border-black/[0.06]">
                <div className="flex gap-1 mb-4">
                  {[...Array(5)].map((_, i) => (
                    <span key={i} style={{ color: "#F4A432", fontSize: "14px" }}>
                      ★
                    </span>
                  ))}
                </div>
                <p className="font-serif text-base text-black leading-relaxed mb-5">
                  &quot;Every agency we&apos;d used before measured success in leads. Social
                  Manch measured it in pipeline. That single shift in how they
                  defined success changed everything about the quality of what they
                  delivered.&quot;
                </p>
                <div className="flex items-center gap-3">
                  <div
                    className="w-9 h-9 rounded-full flex items-center justify-center text-xs font-semibold flex-shrink-0"
                    style={{ backgroundColor: "#F4A43220", color: "#F4A432" }}
                  >
                    DP
                  </div>
                  <div>
                    <p className="text-xs font-semibold text-black">Dev Patel</p>
                    <p className="text-[10px] text-gray-400">
                      Founder & CEO, Meridian Analytics
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Container>
      </section>

      {/* ── WHO IT'S FOR ── */}
      <div className="space-y-4">
        {whoItems.map((item, i) => (
          <div
            key={item.label}
            ref={whoRevealRefs[i]}
            style={whoRevealStyles[i]}
            className="bg-white rounded-2xl p-5 sm:p-6 border border-black/[0.06] flex flex-col sm:flex-row gap-3 sm:gap-5 items-start"
          >
            <span
              className="inline-block text-[10px] font-bold tracking-widest uppercase px-3 py-1 rounded-full self-start sm:mt-0.5 flex-shrink-0"
              style={{
                backgroundColor: item.color + "18",
                color: item.color,
              }}
            >
              {item.label}
            </span>
            <p className="text-gray-500 text-sm leading-relaxed">
              {item.description}
            </p>
          </div>
        ))}
      </div>

      {/* ── FAQ ── */}
      <section className="border-t border-black/10 py-16 sm:py-24">
        <Container>
          <div className="grid grid-cols-1 lg:grid-cols-[1fr_2fr] gap-10 lg:gap-20 items-start">
            <div ref={faqLeftRef} style={faqLeftStyle} className="lg:sticky lg:top-28">
              <SectionLabel color="#E8456A">✦ FAQ</SectionLabel>
              <h2 className="font-serif text-3xl sm:text-4xl lg:text-5xl font-normal text-black leading-snug">
                Questions<br />we always<br />get asked.
              </h2>
            </div>
            <div>
              {faqs.map((faq, i) => (
                <FAQItem key={i} faq={faq} index={i} />
              ))}
            </div>
          </div>
        </Container>
      </section>

      {/* ── CTA ── */}
      <section className="relative overflow-hidden bg-[#1a1a1a] py-20 sm:py-28">
        <div
          className="absolute w-72 h-72 rounded-full bg-[#7B5EA7] opacity-15 -top-20 -right-20 pointer-events-none"
          style={{ animation: "floatA 9s ease-in-out infinite" }}
        />
        <div
          className="absolute w-44 h-44 rounded-full bg-[#E8456A] opacity-15 -bottom-12 left-20 pointer-events-none"
          style={{ animation: "floatB 12s ease-in-out infinite" }}
        />
        <div
          className="absolute w-28 h-28 rounded-full bg-[#F4A432] opacity-15 top-12 left-48 pointer-events-none"
          style={{ animation: "floatA 7s ease-in-out infinite reverse" }}
        />

        <Container className="relative z-10">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-20 items-center">
            <div ref={ctaLeftRef} style={ctaLeftStyle}>
              <p
                className="text-[11px] font-semibold tracking-widest uppercase mb-5"
                style={{ color: "#7B5EA7" }}
              >
                ✦ Ready to Fill Your Pipeline
              </p>
              <h2 className="font-serif text-4xl sm:text-5xl lg:text-5xl xl:text-6xl font-normal italic text-white mb-6 leading-tight">
                Let&apos;s build a lead<br />
                engine your sales<br />
                team trusts.
              </h2>
              <p className="text-white/50 text-sm leading-relaxed mb-10">
                We scope every
                engagement individually — because the right system for a 5-person
                SaaS team looks very different from the right system for an
                enterprise sales floor.
              </p>
              <div className="flex flex-wrap gap-4 items-center">
                <MagneticCTA href="/contact" dark>
                  Start the Conversation →
                </MagneticCTA>
                <a
                  href="/pricing"
                  className="text-[11px] font-semibold tracking-widest uppercase text-white/50 hover:text-white transition-colors duration-200 border-b border-white/20 pb-0.5"
                >
                  View Pricing
                </a>
              </div>
            </div>

            {/* Tier cards */}
            <div
              ref={ctaRightRef}
              style={ctaRightStyle}
              className="bg-white/8 border border-white/10 rounded-3xl p-8 space-y-4"
            >
              <p className="text-[10px] font-semibold tracking-widest uppercase text-white/40 mb-6">
                Choose your plan
              </p>

              {[
                {
                  name: "Starter",
                  description: "Perfect for startups and small businesses looking to establish their online presence.",
                  cta: "Get a Quote",
                },
                {
                  name: "Growth",
                  description: "Designed for growing brands that need consistent marketing and measurable results.",
                  cta: "Schedule a Consultation",
                },
                {
                  name: "Enterprise",
                  description: "Fully customized solutions for organizations with complex business requirements.",
                  cta: "Request a Proposal",
                },
              ].map((tier) => (
                <div
                  key={tier.name}
                  className="flex items-start justify-between gap-4 border border-white/10 rounded-2xl p-5"
                >
                  <div className="flex-1 min-w-0">
                    <p className="text-white text-sm font-semibold mb-1">{tier.name}</p>
                    <p className="text-white/50 text-xs leading-relaxed">{tier.description}</p>
                  </div>
                  <a
                    href="/contact"
                    className="flex-shrink-0 text-[10px] font-semibold tracking-widest uppercase text-white border border-white/20 rounded-full px-4 py-2 hover:bg-white hover:text-[#1a1a1a] transition-all duration-200 whitespace-nowrap"
                  >
                    {tier.cta}
                  </a>
                </div>
              ))}
            </div>
          </div>
        </Container>
      </section>

      <style jsx global>{`
        @keyframes floatA {
          0%, 100% { transform: translateY(0px) scale(1); }
          50% { transform: translateY(-18px) scale(1.04); }
        }
        @keyframes floatB {
          0%, 100% { transform: translateY(0px) scale(1); }
          50% { transform: translateY(14px) scale(0.96); }
        }
      `}</style>
    </main >
  );
};

export default LeadGenerationPage;